{{- if .Values.minio.enabled  }}
{{- if .Values.minio.istio.enabled  }}
{{- if .Values.minio.istio.gateway.enabled  }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-minio
  labels:
    {{- include "socialRegistry.labels" . | nindent 4 }}
spec:
  selector:
    {{ toYaml .Values.minio.istio.gateway.ingressController | nindent 4 }}
  servers:
  {{- if .Values.minio.istio.gateway.httpEnabled }}
  - port:
      name: http2
      number: 8080
      protocol: HTTP2
    hosts:
      - {{ default .Values.global.minioHostname .Values.minio.istio.gateway.host | quote }}
    {{- if .Values.minio.istio.gateway.httpTlsRedirect }}
    tls:
      httpsRedirect: true
    {{- end }}
  {{- end }}
  {{- if .Values.minio.istio.gateway.httpsEnabled }}
  - port:
      name: https
      number: 8443
      protocol: HTTPS
    hosts:
      - {{ default .Values.global.minioHostname .Values.minio.istio.gateway.host | quote }}
    tls:
      {{ toYaml (omit .Values.minio.istio.gateway.tls "enabled") | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
